CREATE TABLE ytulist (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    cpassword VARCHAR(255) NOT NULL,
    hashpassword VARCHAR(255) NOT NULL
);

CREATE TABLE ytulistitems (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(255) NOT NULL,
    ytitems VARCHAR(255) NOT NULL,
    itemamount VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sukli (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(255) NOT NULL,
    sukli INT NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);